### ISSUE TITLE
pretraining

### ISSUE THREAD

**Issue by ZAJ0711** [dreamquark-ai/tabnet#251] opened 2020-12-17 10:11 UTC
when i just try the pretraining model
i find that 
1) the loss changes rapidly sometime, such as in three consecutive epochs, the loss from 1.07313 to 20038.68732 and then 1.0001, but it not always happens
2)the output is val_0_unsup_loss and loss, what is the different?
3) i use the model for Binary classification, and the tag is nearly 7:3，and the method of splitting data i use is keep the original proportion of segmentation, but it does not work well, and when i choose the random splitting, it seems better, When the weight parameter in fit function is used,  the original proportion of segmentation is needed?

thanks for your reply !

**Comment by Optimox** [comment] 2020-12-17 13:03
1-  val_0_unsup_loss is the evaluation metric on your first eval_set and loss is the loss on the training set.

The fact that you can see huge increase in `loss` is due (I think) to the random batches, every time all the lines in one batch have a feature with a common unique value that will create a standard deviation of 0 and so the loss is exploding. It does not always happen because there is a random shuffle, so this does not always happen. If you use a larger batch_size you should see this phenomenon less often but smaller batch size might help the pretraining. I think you can safely ignore the fluctuations in the training loss and this should not happen in the `val_0_unsup_loss` (except if your entire validation set has a feature with only one modality).

It's a bit unclear in the paper how they deal with this, it might be improved in the future.

2- I don't think I understood your question. Splitting and sampling strategies are different things. You should split in a way that makes more sense in a business/global point of view - if you have unbalanced data you probably want to keep the proportions in each splits. Then whether it's a good idea to use weights in sampler is independent and should be tested - you should stick with what's working best.

**Comment by Optimox** [comment] 2020-12-24 13:53
@ZAJ0711 any feedback from the Pretrainer? Did you manage to make it work?

**Comment by csetraynor** [comment] 2021-02-28 15:48
Yes, I also found that behaviour happening when using a small batch size. On top of that with categorical variables, the following runtime error also happens for a small batch size of 128. The runtime error can be reproduced with pretraining_examples.py. Maybe I am missing something about why the error happens, it seems obscure to me. However, the error doesn't happen when using the recommended batch size of 2048 with a virtual batch size of 128,


```
unsupervised_model.fit(
    X_train=X_train,
    eval_set=[X_valid],
    max_epochs=max_epochs ,
    patience=5,
    batch_size=128, virtual_batch_size=32,
    num_workers=0,
    drop_last=False,
    pretraining_ratio=0.8
) 
RuntimeErrorTraceback (most recent call last)
<ipython-input-14-9a0b7b5b9588> in <module>
      6     num_workers=0,
      7     drop_last=False,
----> 8     pretraining_ratio=0.8,
      9 )

~/.local/lib/python3.7/site-packages/pytorch_tabnet/pretraining.py in fit(self, X_train, eval_set, eval_name, loss_fn, pretraining_ratio, weights, max_epochs, patience, batch_size, virtual_batch_size, num_workers, drop_last, callbacks, pin_memory)
    147             self._callback_container.on_epoch_begin(epoch_idx)
    148 
--> 149             self._train_epoch(train_dataloader)
    150 
    151             # Apply predict epoch to all eval sets

~/.local/lib/python3.7/site-packages/pytorch_tabnet/pretraining.py in _train_epoch(self, train_loader)
    273             self._callback_container.on_batch_begin(batch_idx)
    274 
--> 275             batch_logs = self._train_batch(X)
    276 
    277             self._callback_container.on_batch_end(batch_idx, batch_logs)

~/.local/lib/python3.7/site-packages/pytorch_tabnet/pretraining.py in _train_batch(self, X)
    305             param.grad = None
    306 
--> 307         output, embedded_x, obf_vars = self.network(X)
    308         loss = self.compute_loss(output, embedded_x, obf_vars)
    309 

/opt/scp/software/PyTorch/1.4.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/.local/lib/python3.7/site-packages/pytorch_tabnet/tab_network.py in forward(self, x)
    364             # set prior of encoder with obf_mask
    365             prior = 1 - obf_vars
--> 366             steps_out, _ = self.encoder(masked_x, prior=prior)
    367             res = self.decoder(steps_out)
    368             return res, embedded_x, obf_vars

/opt/scp/software/PyTorch/1.4.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/.local/lib/python3.7/site-packages/pytorch_tabnet/tab_network.py in forward(self, x, prior)
    158         steps_output = []
    159         for step in range(self.n_steps):
--> 160             M = self.att_transformers[step](prior, att)
    161             M_loss += torch.mean(
    162                 torch.sum(torch.mul(M, torch.log(M + self.epsilon)), dim=1)

/opt/scp/software/PyTorch/1.4.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/.local/lib/python3.7/site-packages/pytorch_tabnet/tab_network.py in forward(self, priors, processed_feat)
    635         x = self.bn(x)
    636         x = torch.mul(x, priors)
--> 637         x = self.selector(x)
    638         return x
    639 

/opt/scp/software/PyTorch/1.4.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/.local/lib/python3.7/site-packages/pytorch_tabnet/sparsemax.py in forward(self, input)
    202 
    203     def forward(self, input):
--> 204         return entmax15(input, self.dim)
    205 
    206 

~/.local/lib/python3.7/site-packages/pytorch_tabnet/sparsemax.py in forward(ctx, input, dim)
    125         input = input / 2  # divide by 2 to solve actual Entmax
    126 
--> 127         tau_star, _ = Entmax15Function._threshold_and_support(input, dim)
    128         output = torch.clamp(input - tau_star, min=0) ** 2
    129         ctx.save_for_backward(output)

~/.local/lib/python3.7/site-packages/pytorch_tabnet/sparsemax.py in _threshold_and_support(input, dim)
    157 
    158         support_size = (tau <= Xsrt).sum(dim).unsqueeze(dim)
--> 159         tau_star = tau.gather(dim, support_size - 1)
    160         return tau_star, support_size
    161 

RuntimeError: Invalid index in gather at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:657
```

**Comment by Optimox** [comment] 2021-03-01 08:42
Thanks, I need to have a look. Don't have much time at the moment but will do thanks!

**Comment by Optimox** [comment] 2021-12-03 17:08
I'm closing this as #341 will probably solve a similar issue.

**Closed by Optimox** 2021-12-03 17:08 UTC
