### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'n_indep_decoder'

### ISSUE THREAD

**Issue by balazsgonczy** [dreamquark-ai/tabnet#374] opened 2022-03-23 22:04 UTC
Hi, 

I am trying to load a saved Tabnet model trained with your github repo.

Code:
from pytorch_tabnet.tab_model import TabNetClassifier
loaded_clf = TabNetClassifier()
loaded_clf.load_model("C:/Users/goncz/Desktop/test_model.zip")

Error message:
###
Device used : cpu
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3000/3925200397.py in <module>
      1 loaded_clf = TabNetClassifier()
----> 2 loaded_clf.load_model("C:/Users/goncz/Desktop/test_model.zip")
      3 

~\AppData\Local\Programs\Orange\lib\site-packages\pytorch_tabnet\abstract_model.py in load_model(self, filepath)
    409             raise KeyError("Your zip file is missing at least one component")
    410 
--> 411         self.__init__(**loaded_params["init_params"])
    412 
    413         self._set_network()

TypeError: __init__() got an unexpected keyword argument 'n_indep_decoder'
###

**Comment by balazsgonczy** [comment] 2022-03-23 22:05
If you could investigate it asap that would be nice. :)

Thank you very much in advance!

**Comment by balazsgonczy** [comment] 2022-03-23 22:17
Yes if you init the tabnet algo with this code "loaded_clf = TabNetClassifier()" then the 'n_indep_decoder' is going to be missed from the model. So it won't be able to load it.

**Comment by Optimox** [comment] 2022-03-24 08:50
Hello @balazsgonczy,

Can you share a bit more information and ideally a reproducible error code where you save a model that can't be loaded back?

**Comment by balazsgonczy** [comment] 2022-03-24 09:11
Hello @Optimox,

I have used the forest example on my own data. Then I saved the model. There I could load it back without issue. But if I wanted to load the model to a new Jupyther notebook then it didn't worked. So I have to retrain the model each time I run my workflow in order to proceed with my task.

The main issue is what I have written. When you load back a model and before that you init the model like this: loaded_clf = TabNetClassifier() it won't match your saved model. Also I tried to init the missing parts like this: loaded_clf ="TabNetClassifier(n_indep_decoder=1)", but it retrieved the same error message. 

I think the error arises from the init not being able to predefine certain parameters like shadder or indep_decoder. So I would check it out.

What considers the reproducible code... It is for a competition so I can only share it after the deadline.

Best,

Balázs

**Comment by Optimox** [comment] 2022-03-24 09:50
I think what is most likely is that you have different version of pytorch-tabnet install in your different environments. So when you save your model the architectecture is different between the two environments, hence your error when loading.

Can you make sure that both environments have the exact same version and retry ?

**Comment by Optimox** [comment] 2022-03-24 11:53
About reproducible errors : you do not need to give your full code (also it's better if I don't need to review an entire pipeline).

You should be able to reproduce your error with a randomly generated X_train, y_train.

If you manage to reproduce your error within a very simple setting that can be reproduce I can investigate directly what is going on. Otherwise I'm in the dark.

**Comment by balazsgonczy** [comment] 2022-03-24 13:34
pytorch_tabnet version: NA - in the forest notebook?

**Comment by balazsgonczy** [comment] 2022-03-24 13:35
I doubt this could be the issue. I am using Vscode + Jupyther Notebook with similar packages. I haven't created virtual environment for them so...

**Comment by Optimox** [comment] 2022-03-25 09:07
how are you installing pytorch-tabnet ? with pip? from source?

what is the result of `pip list` for pytorch-tabnet on both environments?

**Comment by Optimox** [comment] 2022-03-29 08:07
@balazsgonczy any news?

**Comment by Optimox** [comment] 2022-04-04 21:35
I'm closing this since I'm not able to reproduce the error, please reopen with more information or a reproducible code.

**Closed by Optimox** 2022-04-04 21:35 UTC
Labels: bug
