### ISSUE TITLE
Add cat_dims params in readme

### ISSUE THREAD

**Issue by Forbu** [dreamquark-ai/tabnet#233] opened 2020-11-12 17:08 UTC
## Feature request

**What is the expected behavior?**
To be operational after reading the readme for a user like me

**What is motivation or use case for adding/changing the behavior?**
I lost 30 min looking for what was missing in my code. 

**How should this be implemented in your opinion?**
Just modify the readme

**Are you willing to work on this yourself?**
yes : we could just add this line in the list of parameters in the readme :
cat_dims : list of int (default =[]) giving the list of input dimension of the categorical variables (basicly the number of unique value of your categorical variables)

I know it's really not a big request but I didn't know how to do it ^^.

**Comment by Forbu** [comment] 2020-11-12 17:17
And also if you write cat_emb_dim=1 and you didn't write any parameters for cat_dims, you are trick into thinking you are doing embedding (because their is no bug) but there is no embedding training, you are training on raw int.

**Comment by Optimox** [comment] 2020-12-06 11:40
I'm closing this as a duplicate of #226

**Closed by Optimox** 2020-12-06 11:40 UTC
Labels: enhancement
