### ISSUE TITLE
Other Optimizers

### ISSUE THREAD

**Issue by trulicup** [dreamquark-ai/tabnet#236] opened 2020-11-15 20:48 UTC
## Feature request
Allow users to use other optimizers aside from adam.

**What is the expected behavior?**
Increase performance or training speed by trying out different optimizers.

**What is motivation or use case for adding/changing the behavior?**
It will give users more flexibility to use whatever optimizer they feel will work better for their problem.

**How should this be implemented in your opinion?**
Change the optimizer parameter to take any pytorch optimizer and not just adam.

**Are you willing to work on this yourself?**
yes.

**Comment by Optimox** [comment] 2020-11-15 20:51
Have you tried optimizer parameter?

**Comment by trulicup** [comment] 2020-11-15 20:57
I have, but when I tried to use SparseAdam I got this error:

> ValueError: optimizer got an empty parameter list

**Comment by Optimox** [comment] 2020-11-15 21:19
Have you tried optimizer_params?

**Comment by trulicup** [comment] 2020-11-15 21:26
> I have, but when I tried to use SparseAdam I got this error:
> 
> > ValueError: optimizer got an empty parameter list
> 
> These were my parameters:
> 
> > tabnet_params = dict(
> > n_d = 16,
> > n_a = 16,
> > n_steps = 5,
> > n_independent = 2,
> > n_shared = 1,
> > gamma = 1.5,
> > momentum = 0.7,
> > lambda_sparse = 1e-7,
> > optimizer_fn = optim.SparseAdam,
> > optimizer_params = dict(lr = 2e-2),
> > mask_type = "entmax",
> > scheduler_params = dict(
> > mode = "min", patience = 5, min_lr = 1e-5, factor = 0.9),
> > scheduler_fn = ReduceLROnPlateau,
> > seed = seed,
> > verbose = 5
> > )

Yeah. Thats what I did here.

**Comment by Optimox** [comment] 2020-11-15 21:43
Well, I'm asking questions because the code is already supposed to accept any pytorch optimizer. There is nothing specific to Adam in the code, it's just the default optimizer.

Does your code run if you replace `torch.optim.SparseAdam` by `torch.optim.Adam`? What happens with `torch.optim.SGD`?

So the feature you are requesting is supposed to be already available. If something does not work, could you share a reproducible code so that we can reproduce and fix what's wrong?

When I'm trying SparseAdam I get this error (which is no big surprise):
`RuntimeError: SparseAdam does not support dense gradients, please consider Adam instead`

So you can use classical optimizers, but since Tabnet does not produce sparse gradients I would consider Adam instead.

But it seem that your error has nothing to do with Adam or SparseAdam, I think your network is not defined and that you don't have parameters to give to the optimizer. But this should never happen when using pytorch-tabnet. Could you share some reproducible code please?

**Comment by Optimox** [comment] 2020-11-15 21:52
I just tried a bunch of different optimizers from torch.optim they all seem to be working fine.

**Comment by trulicup** [comment] 2020-11-15 21:58
Here is the notebook for my code:
https://colab.research.google.com/drive/1YPUw976g7irc1qJkLVPC2ttHPuw61i9g?usp=sharing

**Comment by Optimox** [comment] 2020-11-16 15:23
Well I guess you'll find plenty of help for the Kaggle competition if you share a notebook with the corresponding error.

I can't review everyone's code. I tried to reproduce your error but couldn't so I'm closing this. Feel free to reopen with a minimal reproducible error when  you have one.

**Closed by Optimox** 2020-11-16 15:23 UTC
Labels: enhancement
