### ISSUE TITLE
Mask based on raw feature instead of embedded vector

### ISSUE THREAD

**Issue by weiguowilliam** [dreamquark-ai/tabnet#398] opened 2022-06-07 18:38 UTC
## Feature request

Currently model first embed features into embedded vectors and then randomly mask some item of the vectors. So maybe only part of a feature representation if masked. For example, feature a is embedded as [1,2,3] and then get masked as [x,2,x]. I wonder if we can add mask based on raw feature, which means the whole embedded vector for the same feautre is masked. For example, in this case the whole feature vector [1,2,3] is detected as the same feature and get masked together as [x,x,x]. Thanks a lot.

**What is the expected behavior?**

Add mask based on feature instead of vector position.

**What is motivation or use case for adding/changing the behavior?**

Masking the entire feature may help encourage model to learn better embedding representation.

**How should this be implemented in your opinion?**

Change the order of masking and embedding.

**Are you willing to work on this yourself?**

**Comment by Optimox** [comment] 2022-06-08 08:12
Hi,
I think this is a duplicate of #122.

Feel free to reopen if I did not understand correctly and that you feel that it's a different proposal.

**Closed by Optimox** 2022-06-08 08:12 UTC
Labels: enhancement
